CREATE TABLE IF NOT EXISTS prod_source.vtasalestable (
   INVENTTRANSORIGIN	UInt64,
   RETURNINVENTTRANSORIGIN	UInt64,
   SALESID	String,
   SALESIDRETURN	String,
   MODIFIEDBY	String,
   MODIFIEDTRANSACTIONID	UInt64,
   CREATEDDATETIME	DateTime,
   CREATEDBY	String,
   DATAAREAID	String,
   RECVERSION	Int64,
   PARTITION	UInt64,
   RECID	UInt64,
   last_synced_at               DateTime,
   updated_at    DateTime DEFAULT now(),
   PRIMARY KEY (RECID)
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (RECID, CREATEDDATETIME)
PARTITION BY toYYYYMM(CREATEDDATETIME)
TTL CREATEDDATETIME + INTERVAL 5 YEAR DELETE
SETTINGS index_granularity = 8192