CREATE TABLE IF NOT EXISTS prod_source.retailtransactiondiscounttrans (
   AMOUNT	Float64,
   CHANNEL	UInt64,
   CUSTOMERDISCOUNTTYPE	Int64,
   DEALPRICE	Float64,
   DISCOUNTAMOUNT	Float64,
   DISCOUNTCODE	String,
   DISCOUNTORIGINTYPE	UInt32,
   LINENUM	UInt32,
   MANUALDISCOUNTTYPE	UInt32,
   ORIGIN	String,
   PERCENTAGE	Float64,
   PERIODICDISCOUNTOFFERID	String,
   REPLICATIONCOUNTERFROMORIGIN	Int64,
   SALELINENUM	UInt32,
   STOREID	String,
   TERMINALID	String,
   TRANSACTIONID	String,
   DISCOUNTCOST	Float64,
   DATAAREAID	String,
   RECVERSION	Int64,
   PARTITION	UInt64,
   RECID	UInt64,
   MODIFIEDDATETIME	DateTime,
   updated_at    DateTime DEFAULT now(),
   PRIMARY KEY (RECID)
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (RECID, MODIFIEDDATETIME)
PARTITION BY toYYYYMM(MODIFIEDDATETIME)
TTL MODIFIEDDATETIME + INTERVAL 5 YEAR DELETE
SETTINGS index_granularity = 8192