clickhouse:
  host: "ofvssfn5dd.us-central1.gcp.clickhouse.cloud"
  port: 8443
  user: "default"
  password: "upU57JMLE.d30"
  databases:
    prod_source:  
      name: "prod_source"
      tables:
        salesline:
          table_name: "salesline"
          engine: "ReplacingMergeTree"
          order_by: ["RECID", "CREATEDDATETIME"]
          primary_key: "RECID"

        custinvoicejour:
          table_name: "custinvoicejour"
          engine: "ReplacingMergeTree"
          order_by: ["RECID", "INVOICEDATE"]
          primary_key: "RECID"

    prod_dwh: 
      name: "prod_dw"